### ISSUE TITLE
Missing .csproj file.

### ISSUE THREAD

**Issue by Xeddius** [Jfaler/soup#6]
Please upload the .csproj file for Visual Studio as this may allow easier building for cross platform capabilities using the mono project's xbuild*. 
(GNU/Linux and OSX/MacOS support) 

*or consider a mono port.

**Comment by giant995** [comment]
We the new .NET core you can now build multiplatform apps. It's now open source and supported my Microsoft

**Comment by giant995** [comment]
Why is there no communication from the repo owner? I've seen some issues closed without any answers.
